# Copyright (c) - Graphical Playground. All rights reserved.
# For more information, see https://graphical-playground/legal
# mailto:support AT graphical-playground DOT com

# Generate the ASCII escape character
string(ASCII 27 GPBT_ASCII_ESCAPE)

# Regular colors
set(GPBT_COLOR_FG_BLACK  "${GPBT_ASCII_ESCAPE}[0;30m")
set(GPBT_COLOR_FG_RED    "${GPBT_ASCII_ESCAPE}[0;31m")
set(GPBT_COLOR_FG_GREEN  "${GPBT_ASCII_ESCAPE}[0;32m")
set(GPBT_COLOR_FG_YELLOW "${GPBT_ASCII_ESCAPE}[0;33m")
set(GPBT_COLOR_FG_BLUE   "${GPBT_ASCII_ESCAPE}[0;34m")
set(GPBT_COLOR_FG_PURPLE "${GPBT_ASCII_ESCAPE}[0;35m")
set(GPBT_COLOR_FG_CYAN   "${GPBT_ASCII_ESCAPE}[0;36m")
set(GPBT_COLOR_FG_WHITE  "${GPBT_ASCII_ESCAPE}[0;37m")

# Bold colors
set(GPBT_COLOR_FG_BOLD_BLACK  "${GPBT_ASCII_ESCAPE}[1;30m")
set(GPBT_COLOR_FG_BOLD_RED    "${GPBT_ASCII_ESCAPE}[1;31m")
set(GPBT_COLOR_FG_BOLD_GREEN  "${GPBT_ASCII_ESCAPE}[1;32m")
set(GPBT_COLOR_FG_BOLD_YELLOW "${GPBT_ASCII_ESCAPE}[1;33m")
set(GPBT_COLOR_FG_BOLD_BLUE   "${GPBT_ASCII_ESCAPE}[1;34m")
set(GPBT_COLOR_FG_BOLD_PURPLE "${GPBT_ASCII_ESCAPE}[1;35m")
set(GPBT_COLOR_FG_BOLD_CYAN   "${GPBT_ASCII_ESCAPE}[1;36m")
set(GPBT_COLOR_FG_BOLD_WHITE  "${GPBT_ASCII_ESCAPE}[1;37m")

# Underlined colors
set(GPBT_COLOR_FG_UNDERLINED_BLACK  "${GPBT_ASCII_ESCAPE}[4;30m")
set(GPBT_COLOR_FG_UNDERLINED_RED    "${GPBT_ASCII_ESCAPE}[4;31m")
set(GPBT_COLOR_FG_UNDERLINED_GREEN  "${GPBT_ASCII_ESCAPE}[4;32m")
set(GPBT_COLOR_FG_UNDERLINED_YELLOW "${GPBT_ASCII_ESCAPE}[4;33m")
set(GPBT_COLOR_FG_UNDERLINED_BLUE   "${GPBT_ASCII_ESCAPE}[4;34m")
set(GPBT_COLOR_FG_UNDERLINED_PURPLE "${GPBT_ASCII_ESCAPE}[4;35m")
set(GPBT_COLOR_FG_UNDERLINED_CYAN   "${GPBT_ASCII_ESCAPE}[4;36m")
set(GPBT_COLOR_FG_UNDERLINED_WHITE  "${GPBT_ASCII_ESCAPE}[4;37m")

# High intensity colors
set(GPBT_COLOR_FG_HI_BLACK  "${GPBT_ASCII_ESCAPE}[0;90m")
set(GPBT_COLOR_FG_HI_RED    "${GPBT_ASCII_ESCAPE}[0;91m")
set(GPBT_COLOR_FG_HI_GREEN  "${GPBT_ASCII_ESCAPE}[0;92m")
set(GPBT_COLOR_FG_HI_YELLOW "${GPBT_ASCII_ESCAPE}[0;93m")
set(GPBT_COLOR_FG_HI_BLUE   "${GPBT_ASCII_ESCAPE}[0;94m")
set(GPBT_COLOR_FG_HI_PURPLE "${GPBT_ASCII_ESCAPE}[0;95m")
set(GPBT_COLOR_FG_HI_CYAN   "${GPBT_ASCII_ESCAPE}[0;96m")
set(GPBT_COLOR_FG_HI_WHITE  "${GPBT_ASCII_ESCAPE}[0;97m")

# Bold High intensity colors
set(GPBT_COLOR_FG_HI_BOLD_BLACK  "${GPBT_ASCII_ESCAPE}[1;90m")
set(GPBT_COLOR_FG_HI_BOLD_RED    "${GPBT_ASCII_ESCAPE}[1;91m")
set(GPBT_COLOR_FG_HI_BOLD_GREEN  "${GPBT_ASCII_ESCAPE}[1;92m")
set(GPBT_COLOR_FG_HI_BOLD_YELLOW "${GPBT_ASCII_ESCAPE}[1;93m")
set(GPBT_COLOR_FG_HI_BOLD_BLUE   "${GPBT_ASCII_ESCAPE}[1;94m")
set(GPBT_COLOR_FG_HI_BOLD_PURPLE "${GPBT_ASCII_ESCAPE}[1;95m")
set(GPBT_COLOR_FG_HI_BOLD_CYAN   "${GPBT_ASCII_ESCAPE}[1;96m")
set(GPBT_COLOR_FG_HI_BOLD_WHITE  "${GPBT_ASCII_ESCAPE}[1;97m")

# Background
set(GPBT_COLOR_BG_BLACK  "${GPBT_ASCII_ESCAPE}[40m")
set(GPBT_COLOR_BG_RED    "${GPBT_ASCII_ESCAPE}[41m")
set(GPBT_COLOR_BG_GREEN  "${GPBT_ASCII_ESCAPE}[42m")
set(GPBT_COLOR_BG_YELLOW "${GPBT_ASCII_ESCAPE}[43m")
set(GPBT_COLOR_BG_BLUE   "${GPBT_ASCII_ESCAPE}[44m")
set(GPBT_COLOR_BG_PURPLE "${GPBT_ASCII_ESCAPE}[45m")
set(GPBT_COLOR_BG_CYAN   "${GPBT_ASCII_ESCAPE}[46m")
set(GPBT_COLOR_BG_WHITE  "${GPBT_ASCII_ESCAPE}[47m")

# High intensity background colors
set(GPBT_COLOR_BG_HI_BLACK  "${GPBT_ASCII_ESCAPE}[0;100m")
set(GPBT_COLOR_BG_HI_RED    "${GPBT_ASCII_ESCAPE}[0;101m")
set(GPBT_COLOR_BG_HI_GREEN  "${GPBT_ASCII_ESCAPE}[0;102m")
set(GPBT_COLOR_BG_HI_YELLOW "${GPBT_ASCII_ESCAPE}[0;103m")
set(GPBT_COLOR_BG_HI_BLUE   "${GPBT_ASCII_ESCAPE}[0;104m")
set(GPBT_COLOR_BG_HI_PURPLE "${GPBT_ASCII_ESCAPE}[0;105m")
set(GPBT_COLOR_BG_HI_CYAN   "${GPBT_ASCII_ESCAPE}[0;106m")
set(GPBT_COLOR_BG_HI_WHITE  "${GPBT_ASCII_ESCAPE}[0;107m")

# Misc
set(GPBT_COLOR_RESET "${GPBT_ASCII_ESCAPE}[0m")
